//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumaneSociety.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
//<<<<<<< HEAD
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DEJANB8EA\\SQLEXPRESS;Initial Catalog=HumaneSociety;Integrated Securit" +
            "y=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False")]
        public string HumaneSocietyConnectionString {
            get {
                return ((string)(this["HumaneSocietyConnectionString"]));
//=======
//        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-3B575C3\\SQLEXPRESS;Initial Catalog=HumaineSpciety;Integrated " +
//            "Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False")]
//        public string HumaineSpcietyConnectionString {
//            get {
//                return ((string)(this["HumaineSpcietyConnectionString"]));
//>>>>>>> 4e72e0a742d69f81206dccb563b31acd15f1b5d5
            }
        }
    }
}
